Repository searx/searx, pull requests merged in 2018-08, with the labels that each got.

#933 searx fetchs automaticaly firefox last versions
  searx/data/useragents.json
  searx/utils.py
  utils/fetch_firefox_version.py
Labels: core

#1366 Fix etymonline engine
  searx/settings.yml
Labels: engine

#1233 Use new LABEL syntax for Dockerfile
  Dockerfile
Labels: docker
