Repository searx/searx, pull requests merged in 2020-12, with the labels that each got.

#2345 [mod] oscar theme: added option into gruntfile.js for generate sourceMap
  searx/static/themes/oscar/gruntfile.js
  searx/static/themes/oscar/js/searx.min.js
  searx/static/themes/oscar/js/searx.min.js.map
Labels: theme

#2291 [enh] user settings can relied on the default settings
  docs/admin/settings.rst
  docs/blog/private-engines.rst
  searx/__init__.py
  searx/exceptions.py
  searx/settings_loader.py
  tests/unit/settings/empty_settings.yml
  tests/unit/settings/syntaxerror_settings.yml
  tests/unit/settings/user_settings.yml
  tests/unit/settings/user_settings_keep_only.yml
  tests/unit/settings/user_settings_remove.yml
  tests/unit/settings/user_settings_remove2.yml
  tests/unit/settings/user_settings_simple.yml
  tests/unit/test_settings_loader.py
Labels: core

#2318 Add pylint
  Makefile
  searx/engines/__init__.py
  searx/engines/acgsou.py
  searx/engines/arxiv.py
  searx/engines/base.py
  searx/engines/bing_images.py
  searx/engines/bing_news.py
  searx/engines/bing_videos.py
  searx/engines/currency_convert.py
  searx/engines/duckduckgo.py
  searx/engines/duckduckgo_definitions.py
  searx/engines/duckduckgo_images.py
  searx/engines/filecrop.py
  searx/engines/google_images.py
  searx/engines/google_news.py
  searx/engines/peertube.py
  searx/engines/pubmed.py
  searx/engines/wikidata.py
  searx/engines/yahoo_news.py
  searx/plugins/__init__.py
  searx/query.py
  searx/results.py
  searx/search.py
  searx/utils.py
  searx/webapp.py
  tests/test_robot.py
  tests/unit/test_plugins.py
  tests/unit/test_preferences.py
  tests/unit/test_webapp.py
Labels: core

#2285 bugfix & refactor digg engine
  Makefile
  searx/engines/digg.py
Labels: engine

#2332 [enh] record exception details per engine
  docs/dev/engine_overview.rst
  searx/engines/1337x.py
  searx/engines/__init__.py
  searx/engines/acgsou.py
  searx/engines/ahmia.py
  searx/engines/apkmirror.py
  searx/engines/archlinux.py
  searx/engines/arxiv.py
  searx/engines/bing_news.py
  searx/engines/duckduckgo_images.py
  searx/engines/elasticsearch.py
  searx/engines/google.py
  searx/engines/google_images.py
  searx/engines/google_videos.py
  searx/engines/xpath.py
  searx/engines/youtube_api.py
  searx/exceptions.py
  searx/metrology/__init__.py
  searx/metrology/error_recorder.py
  searx/results.py
  searx/search.py
  searx/utils.py
  searx/webapp.py
  tests/unit/test_utils.py
Labels: api, core

#2338 add new issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/engine-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: enhancement

#2362 [doc] recommend to use 'use_default_settings=True'
  .config.sh
  docs/admin/installation-searx.rst
  docs/admin/settings.rst
  docs/build-templates/searx.rst
  utils/searx.sh
  utils/templates/etc/searx/use_default_settings.yml
Labels: doc

#2358 [fix] command engine: SearchQuery.query is str not bytes
  searx/engines/command.py
Labels: engine

#2225 Processors
  docs/admin/engines.rst
  docs/dev/engine_overview.rst
  searx/engines/__init__.py
  searx/engines/command.py
  searx/engines/currency_convert.py
  searx/engines/dictzone.py
  searx/engines/translated.py
  searx/search.py
  searx/search/__init__.py
  searx/search/processors/__init__.py
  searx/search/processors/abstract.py
  searx/search/processors/offline.py
  searx/search/processors/online.py
  searx/search/processors/online_currency.py
  searx/search/processors/online_dictionary.py
  searx/webapp.py
  tests/unit/test_search.py
  tests/unit/test_standalone_searx.py
  tests/unit/test_webadapter.py
  utils/standalone_searx.py
Labels: core

#2391 Add link to contact instance maintainer to footer of each page
  Makefile
  searx/brand.py
  searx/templates/oscar/base.html
  searx/templates/simple/base.html
  utils/brand.env
Labels: enhancement

#2398 Mod search query
  searx/query.py
  searx/search/__init__.py
  searx/webadapter.py
  tests/unit/test_search.py
  tests/unit/test_standalone_searx.py
Labels: core
