Repository searx/searx, pull requests merged in 2020-09, with the labels that each got.

#2128 Add command line engines: git grep, find, etc.
  searx/engines/command.py
  searx/settings.yml
  searx/templates/oscar/result_templates/key-value.html
  tests/unit/engines/test_command.py
Labels: core

#2140 [mod] results.py: code clean up
  searx/results.py
Labels: core

#2190 [fix] searx.utils.HTMLTextExtractor: invalid HTML don't raise an Exception
  searx/utils.py
  tests/unit/test_utils.py
Labels: bug, core

#2205 [fix] simple theme: fix autocomplete
  searx/static/themes/simple/css/searx-rtl.css
  searx/static/themes/simple/css/searx-rtl.min.css
  searx/static/themes/simple/css/searx.css
  searx/static/themes/simple/css/searx.min.css
  searx/static/themes/simple/js/searx.head.min.js
  searx/static/themes/simple/js/searx.js
  searx/static/themes/simple/js/searx.min.js
  searx/static/themes/simple/js/searx.min.js.map
  searx/static/themes/simple/js/searx_src/searx_search.js
Labels: bug, theme

#1865 [enh] Docker image: uwsgi serves the static files directly.
  Dockerfile
  dockerfiles/uwsgi.ini
Labels: docker

#2198 [mod] refactor searx.webapp.get_locale
  searx/webapp.py
Labels: core

#2208 [mod] add searx/webutils.py
  searx/utils.py
  searx/webapp.py
  searx/webutils.py
  tests/unit/test_utils.py
  tests/unit/test_webutils.py
Labels: core

#2196 [mod] searx.search.Search: split the search method into different methods
  searx/search.py
Labels: core

#2199 [mod] upgrade requests to version 2.24.0. pyopenssl becomes optional.
  requirements.txt
  searx/__init__.py
  searx/poolrequests.py
  searx/webapp.py
Labels: core, security

#2210 [fix] requirements-dev.txt: set versions for all sphinx* packages
  Makefile
  requirements-dev.txt
  utils/makefile.sphinx
Labels: doc

#2189 Architecture clean up
  searx/query.py
  searx/search.py
  searx/webadapter.py
  searx/webapp.py
  tests/unit/test_search.py
  tests/unit/test_webadapter.py
  utils/standalone_searx.py
Labels: core

#2230 [fix] Sphinx 3.2.1 build: add missing "engines" variable in the jinja context
  docs/conf.py
Labels: bug, doc
