Repository searx/searx, pull requests merged in 2020-07, with the labels that each got.

#2027 Created new plugin type custom_results. Added new plugin bang_redirect
  AUTHORS.rst
  docs/dev/plugins.rst
  searx/data/bangs.json
  searx/external_bang.py
  searx/query.py
  searx/results.py
  searx/search.py
  searx/webapp.py
  tests/unit/test_search.py
  tests/unit/test_webapp.py
Labels: core, search syntax, ui / ux

#2038 Add PR template and contribution guidelines
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE.md
Labels: doc, maintainer, meta

#2043 [fix] external_bang - UnicodeDecodeError: 'ascii' codec can't decode
  utils/templates/etc/uwsgi/apps-archlinux/searx.ini
  utils/templates/etc/uwsgi/apps-archlinux/searx.ini:socket
  utils/templates/etc/uwsgi/apps-available/searx.ini
  utils/templates/etc/uwsgi/apps-available/searx.ini:socket
Labels: bug

#2091 [enh] update documentation about docker
  .dockerignore
  dockerfiles/docker-entrypoint.sh
  docs/admin/installation-docker.rst
Labels: doc

#2104 Add Gitea engine with Codeberg backend
  searx/settings.yml
Labels: engine, enhancement
