Repository searx/searx, pull requests merged in 2020-06, with the labels that each got.

#983 Update results.less
  searx/static/themes/oscar/less/logicodev/results.less
Labels: ui / ux

#1986 Configurable category order
  searx/settings.yml
  searx/webapp.py
Labels: core, enhancement

#2024 [blog post] Developing in Linux containers
  docs/admin/installation-uwsgi.rst
  docs/blog/index.rst
  docs/blog/lxcdev-202006.rst
  docs/utils/lxc.sh.rst
  utils/searx.sh
Labels: doc
