Repository searx/searx, pull requests merged in 2021-01, with the labels that each got.

#2448 [fix] Library Genesis links shifted by 1 #1998
  searx/settings.yml
Labels: engine

#2447 add notice for the issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/engine-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: enhancement

#2457 Fixed typo
  docs/dev/search_api.rst
Labels: doc

#2458 Hide links panel in mobile screens
  searx/templates/oscar/results.html
Labels: theme

#2451 [Fix] Invidious Engine
  searx/engines/invidious.py
  searx/settings.yml
Labels: engine

#2452 Add wiby.me engine
  searx/settings.yml
Labels: theme
